#include "G4MCPLGenerator.hh"
#include "Config.hh"
#include "G4ParticleGun.hh"
#include "G4RunManager.hh"
#include "G4SystemOfUnits.hh"
#include "G4IonTable.hh"
#include "G4ios.hh"
#include <cassert>
#include <G4ParticleDefinition.hh>
#include "G4Threading.hh"

using namespace std;

G4double event_number;

#include "G4AutoLock.hh"

G4ThreadLocal G4int local_event_number;
G4ThreadLocal G4int initial_local_event_number = 0;
G4ThreadLocal G4int updated_local_event_number;
G4ThreadLocal G4int flag; // flaggin the event with event ID = 0 !!

namespace { G4Mutex MCPLMutex = G4MUTEX_INITIALIZER;}

std::vector<int> data_event_num;

G4MCPLGenerator::G4MCPLGenerator(Config& config)
	: G4VUserPrimaryGeneratorAction(),
	m_currentPDG(0),m_currentPartDef(0),m_nUnknownPDG(0),Conf(config)
{
	m_mcplfile.internal = 0;
	G4AutoLock lock(&MCPLMutex);
}

G4MCPLGenerator::~G4MCPLGenerator()
{
  if (m_nUnknownPDG) {
    std::ostringstream cmt;
    cmt << "Ignored a total of " << m_nUnknownPDG
        << " particles in input due to untranslatable pdg codes";
    G4Exception("G4MCPLGenerator::~G4MCPLGenerator()", "G4MCPLGenerator07",
                JustWarning, cmt.str().c_str());
  }
  if (m_mcplfile.internal)
    mcpl_close_file(m_mcplfile);
  delete m_gun;
}

bool G4MCPLGenerator::UseParticle(const mcpl_particle_t* m_p) const
{
	bool use=true;
	switch(abs(m_p->pdgcode)){ // skip neutrinos in MCPL file
		case 12:
			use=false;
			break;
		case 14:
			use=false;
			break;
		case 16:
			use=false;
			break;
	}
	return use;
}

void G4MCPLGenerator::GeneratePrimaries(G4Event* evt)
{
	G4AutoLock lock(&MCPLMutex);
	local_event_number = event_number; //_MCPL
	event_number++;
	if (local_event_number == 0){flag = 1;} //_MCPL

	if (!m_mcplfile.internal) {
		//Initialise:
		m_inputFile= Conf.GetString("MCPL_Inputfile");
		m_mcplfile = mcpl_open_file(m_inputFile.c_str());
		for(uint64_t i=0; i<mcpl_hdr_nparticles(m_mcplfile); i++){
			data_event_num.push_back(1);
		}
		m_gun = new G4ParticleGun(1);
		FindNext();
		if (!m_p) {G4Exception("G4MCPLGenerator::G4MCPLGenerator()", "G4MCPLGenerator01",RunMustBeAborted, "Not a single suitable particle found in input file");}
	}

	if (!m_p) {G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator02",
			RunMustBeAborted, "GeneratePrimaries called despite no suitable"
			" particles existing.");
	G4RunManager::GetRunManager()->AbortRun(false);//hard abort
	return;
	}


	// determines how many events it has to skip (generated by other threads)
	int event_diff = local_event_number - initial_local_event_number;
	if (initial_local_event_number == 0 && flag==0){
		for (int i = initial_local_event_number; i < initial_local_event_number + event_diff; i++){
			FindNextEvent();
		}
	}
	else{
		for (int i = initial_local_event_number+1; i < initial_local_event_number + event_diff; i++){
			FindNextEvent();
		}
	}

	//Transfer m_p info to gun and shoot:
	uint64_t curpos = mcpl_currentposition(m_mcplfile);
	int event_count = FindNextEvent();
	mcpl_seek(m_mcplfile,curpos-1);
	FindNext();
	
	for (int iev=0; iev<event_count; iev++){

		assert(m_currentPDG == m_p->pdgcode && m_currentPartDef);
		m_gun->SetParticleDefinition(m_currentPartDef);
		G4ThreeVector pos(m_p->position[0],m_p->position[1],m_p->position[2]); //m_p->position[2] 
		pos *= cm;
		G4ThreeVector dir(m_p->direction[0],m_p->direction[1],m_p->direction[2]);
		G4ThreeVector pol(m_p->polarisation[0],m_p->polarisation[1],m_p->polarisation[2]);
		double time = m_p->time*ms;
		double weight = m_p->weight;

		m_gun->SetParticleMomentumDirection(dir);
		m_gun->SetParticlePosition(pos);
		m_gun->SetParticleEnergy(m_p->ekin);//already in MeV and CLHEP::MeV=1
		m_gun->SetParticleTime(time); //time
		m_gun->SetParticlePolarization(pol);

		m_gun->GeneratePrimaryVertex(evt);
		evt->GetPrimaryVertex(iev)->GetPrimary(0)->SetWeight(weight);
		//Prepare for next.
		FindNext();//if (initial_local_event_number==0){}
		if (!m_p) {
			G4cout << "G4MCPLGenerator: No more particles to use from input file after this event. Requesting soft abort of run." << G4endl;
			G4RunManager::GetRunManager()->AbortRun(true);//soft abort
		}
	} // end bracket for loop

  initial_local_event_number = local_event_number;
}

void G4MCPLGenerator::FindNext()
{

  while( ( m_p = mcpl_read(m_mcplfile))) {

    if (!UseParticle(m_p))
      continue;

    if (!(m_p->weight>0.0)) {
      G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator03",
                  JustWarning, "Ignoring particle in input with invalid weight.");
      continue;
    }

    if (m_p->pdgcode==0) {
      G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator04",
                  JustWarning, "Ignoring particle in input with invalid pdg code (0).");
      continue;
    }

    if (!LookupPDG(m_p->pdgcode)) {
      ++m_nUnknownPDG;
      if (m_nUnknownPDG<=100) {
        std::ostringstream cmt;
        cmt << "Ignoring particle in input with untranslatable pdg code ("
            << m_p->pdgcode <<")";
        G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator05",
                    JustWarning, cmt.str().c_str());
        if (m_nUnknownPDG==100)
          G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator06",
                      JustWarning, "Limit reached. Suppressing further warnings"
                      " regarding untranslatable pdg codes");
      }
      continue;
    }
    break;
  }
}

int G4MCPLGenerator::FindNextEvent()
{

	int npart=1;
	while( ( m_p = mcpl_read(m_mcplfile))) {

		if (!UseParticle(m_p))
			continue;

		if (!(m_p->weight>0.0)) {
			G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator03",
					JustWarning, "Ignoring particle in input with invalid weight.");
			continue;
		}

		if (m_p->pdgcode==0) {
			G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator04",
					JustWarning, "Ignoring particle in input with invalid pdg code (0).");
			continue;
		}

		if (!LookupPDG(m_p->pdgcode)) {
			++m_nUnknownPDG;
			if (m_nUnknownPDG<=100) {
				std::ostringstream cmt;
				cmt << "Ignoring particle in input with untranslatable pdg code ("
					<< m_p->pdgcode <<")";
				G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator05",
						JustWarning, cmt.str().c_str());
				if (m_nUnknownPDG==100)
					G4Exception("G4MCPLGenerator::GeneratePrimaries()", "G4MCPLGenerator06",
							JustWarning, "Limit reached. Suppressing further warnings"
							" regarding untranslatable pdg codes");
			}
			continue;
		}
		if(m_p->userflags==0){
			npart++;
			continue;
		}
		break;
	}
	return npart;
}

G4ParticleDefinition* G4MCPLGenerator::LookupPDG(G4int pdgcode)
{
  if (m_currentPDG == pdgcode)
    return m_currentPartDef;
  m_currentPDG = pdgcode;
  std::map<G4int,G4ParticleDefinition*>::const_iterator it = m_pdg2pdef.find(pdgcode);
  if (it!=m_pdg2pdef.end()) {
    m_currentPartDef = it->second;
  } else {
    m_currentPartDef = G4ParticleTable::GetParticleTable()->FindParticle(pdgcode);
    if ( !m_currentPartDef && (pdgcode/100000000 == 10)) {
      //Not in ParticleTable and pdgcode is of form 10xxxxxxxx, so look for ion:
      m_currentPartDef = G4IonTable::GetIonTable()->GetIon(pdgcode);
    }
    m_pdg2pdef[pdgcode] = m_currentPartDef;
  }
  return m_currentPartDef;
}

