//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Mar 13 14:50:24 2026 by ROOT version 6.30/02)
//      from the StreamerInfo in file ../simulation_data/KrakowScatter.root
//////////////////////////////////////////////////////////


#ifndef ScintHit_h
#define ScintHit_h
class ScintHit;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>

class ScintHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nHits;       //
   vector<int> side;        //
   vector<int> layer;       //
   vector<int> bar;         //
   vector<double> Edep;        //
   vector<double> Time;        //
   vector<double> Pos_X;       //
   vector<double> Pos_Y;       //
   vector<double> Pos_Z;       //

   ScintHit();
   ScintHit(ScintHit && ) = default;
   ScintHit &operator=(const ScintHit & );
   ScintHit(const ScintHit & );
   virtual ~ScintHit();

   ClassDef(ScintHit,2); // Generated by MakeProject.
};
#endif
