"""
HIBEAM Prototype TPC Analysis — IFJ Krakow CCB Test Beam
=========================================================
Reads 'tracks' via PyROOT SetBranchAddress (bypasses the
cppyy_cast<vector<TrackData>*> error) and 'centroids' via uproot.

Requires:
  recovered_headers/recovered_headers.so   (from TFile::MakeProject)
  pip install uproot awkward scipy matplotlib
"""

import os, glob
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.stats import moyal
from collections import defaultdict
import warnings
warnings.filterwarnings("ignore")

# ─── PyROOT (for tracks branch — memberwise-serialised vector<TrackData>) ────
import ROOT
SO_PATH  = "recovered_headers/recovered_headers.so"
HDR_PATH = "recovered_headers/TrackData.h"   # generated by MakeProject

if not os.path.exists(SO_PATH):
    raise FileNotFoundError(
        f"'{SO_PATH}' not found. Run TFile::MakeProject and compile first.")

ROOT.gSystem.Load(SO_PATH)
ROOT.gROOT.SetBatch(True)   # suppress any canvas popups

# Make the TrackData (and CentroidData) definitions visible to cppyy/JIT.
# gSystem.Load brings in the compiled symbols but does NOT inject the class
# definition into the interpreter — we must do that explicitly.
if os.path.exists(HDR_PATH):
    ROOT.gInterpreter.ProcessLine(f'#include "{HDR_PATH}"')
else:
    # Fallback: declare the struct inline so cppyy can build vector<TrackData>
    ROOT.gInterpreter.Declare("""
        #include <vector>
        class TrackData {
        public:
            int nPoints;
            float slope_xy, intercept_xy, slope_zy, intercept_zy;
            std::vector<int>   y;
            std::vector<float> x, z, charge, sigmas_x, sigmas_z, sigmas_y;
        };
    """)

# ─── Configuration ────────────────────────────────────────────────────────────
CHI2_NDF_MAX      = 25.0
MIN_TRACK_PTS     = 3
LOW_E_PERCENTILE  = 10
HIGH_E_PERCENTILE = 95
MIN_ADC           = 0.0
# ──────────────────────────────────────────────────────────────────────────────

BLUE   = "#2E86AB"
RED    = "#E84855"
ORANGE = "#F4A261"
PURPLE = "#7B2D8B"
GREEN  = "#3BB273"


# ─── Chi²/ndf from TrackData ──────────────────────────────────────────────────

def compute_chi2_ndf(track):
    """
    Two independent linear fits are stored per track:
      x = slope_xy * y + intercept_xy
      z = slope_zy * y + intercept_zy
    ndf = 2*N - 4  (4 free parameters across both projections)
    """
    n = track.nPoints
    if n < MIN_TRACK_PTS:
        return float("inf")

    chi2 = 0.0
    for j in range(n):
        y_j  = float(track.y[j])
        sx   = max(float(track.sigmas_x[j]), 1e-4)
        sz   = max(float(track.sigmas_z[j]), 1e-4)
        chi2 += ((float(track.x[j]) - (track.slope_xy  * y_j + track.intercept_xy)) / sx) ** 2
        chi2 += ((float(track.z[j]) - (track.slope_zy  * y_j + track.intercept_zy)) / sz) ** 2

    ndf = max(2 * n - 4, 1)
    return chi2 / ndf


# ─── Data extraction ──────────────────────────────────────────────────────────

def extract_all_track_data(file_path):
    """
    Use SetBranchAddress so ROOT deserialises vector<TrackData> itself —
    this avoids the cppyy_cast failure from direct tree.tracks access.
    """
    tfile = ROOT.TFile.Open(file_path)
    if not tfile or tfile.IsZombie():
        raise IOError(f"Cannot open {file_path}")
    tree = tfile.Get("trackingData")
    if not tree:
        tfile.Close()
        raise KeyError("'trackingData' tree not found")

    # ── Key fix: pre-allocate the vector and hand its address to ROOT ────────
    tracks_vec = ROOT.std.vector("TrackData")()
    tree.SetBranchAddress("tracks", tracks_vec)

    n_total = n_passed = 0
    all_dedx      = []
    track_records = []
    padrow_hits   = defaultdict(int)
    padrow_dedx   = defaultdict(list)

    for entry_idx in range(tree.GetEntries()):
        tree.GetEntry(entry_idx)

        for track in tracks_vec:
            n = track.nPoints
            if n < MIN_TRACK_PTS:
                continue
            n_total += 1

            # Quality cut
            c2 = compute_chi2_ndf(track)
            if c2 > CHI2_NDF_MAX:
                continue

            # 3-D track length → equidistant deltaX
            x0, x1 = float(track.x[0]),   float(track.x[n-1])
            y0, y1 = float(track.y[0]),   float(track.y[n-1])
            z0, z1 = float(track.z[0]),   float(track.z[n-1])
            length  = np.sqrt((x1-x0)**2 + (y1-y0)**2 + (z1-z0)**2)
            if length < 1e-3:
                continue
            delta_x = length / n

            # Per-centroid dE/dx
            centroid_dedx = []
            centroid_rows = []
            for j in range(n):
                adc = float(track.charge[j])
                if adc <= MIN_ADC:
                    continue
                dv  = adc / delta_x
                centroid_dedx.append(dv)
                row = int(track.y[j])
                centroid_rows.append(row)
                padrow_hits[row] += 1
                padrow_dedx[row].append(dv)

            if not centroid_dedx:
                continue

            n_passed += 1
            all_dedx.extend(centroid_dedx)
            track_records.append({
                "mean_dedx" : float(np.mean(centroid_dedx)),
                "n_points"  : n,
                "length_mm" : length,
                "chi2_ndf"  : c2,
            })

    tfile.Close()
    print(f"  Tracks evaluated     : {n_total}")
    print(f"  Tracks passing cut   : {n_passed}  (chi²/ndf < {CHI2_NDF_MAX})")
    print(f"  dE/dx measurements   : {len(all_dedx)}")
    return (np.array(all_dedx, dtype=float),
            track_records, padrow_hits, padrow_dedx)


# ─── Landau fit ───────────────────────────────────────────────────────────────

def fit_landau(data):
    if len(data) < 50:
        return None, data, 0.0, 0.0
    low_cut  = np.percentile(data, LOW_E_PERCENTILE)
    high_cut = np.percentile(data, HIGH_E_PERCENTILE)
    fit_data = data[(data >= low_cut) & (data <= high_cut)]
    if len(fit_data) < 50:
        return None, fit_data, low_cut, high_cut
    try:
        params = moyal.fit(fit_data)
    except Exception:
        return None, fit_data, low_cut, high_cut
    return params, fit_data, low_cut, high_cut


# ─── Plots ────────────────────────────────────────────────────────────────────

def plot_dedx_fit(ax_main, ax_resid, raw_data, filename):
    params, fit_data, low_cut, high_cut = fit_landau(raw_data)

    ax_main.hist(raw_data, bins=120, density=True,
                 color=BLUE, alpha=0.20, label="All data (raw)")
    counts, bins, _ = ax_main.hist(fit_data, bins=100, density=True,
                                    color=BLUE, alpha=0.65, label="Fit range")
    bin_centers = (bins[:-1] + bins[1:]) / 2

    if params is not None:
        x_smooth = np.linspace(fit_data.min(), fit_data.max(), 500)
        ax_main.plot(x_smooth, moyal.pdf(x_smooth, *params),
                     color=RED, lw=2.5,
                     label=f"Landau fit\nMPV={params[0]:.2f}  Width={params[1]:.2f}")
        fit_pdf = moyal.pdf(bin_centers, *params)
    else:
        fit_pdf = np.zeros_like(bin_centers)
        ax_main.text(0.5, 0.6, "Fit failed", transform=ax_main.transAxes,
                     ha="center", color=RED)

    ax_main.axvline(low_cut,  color=ORANGE, ls="--", lw=1.5,
                    label=f"Low-E cut ({LOW_E_PERCENTILE}th pct)")
    ax_main.axvline(high_cut, color=ORANGE, ls=":",  lw=1.5,
                    label=f"High-E cut ({HIGH_E_PERCENTILE}th pct)")
    ax_main.set_ylabel("Probability Density")
    ax_main.legend(fontsize=8, loc="upper right")
    ax_main.grid(axis="y", alpha=0.3)
    ax_main.set_title(f"dE/dx Distribution — {filename}", fontsize=11)

    residuals = counts - fit_pdf
    ax_resid.bar(bin_centers, residuals, width=(bins[1]-bins[0]),
                 color=PURPLE, alpha=0.7)
    ax_resid.axhline(0, color="black", ls="--", lw=1)
    ax_resid.set_xlabel("dE/dx  [ADC / mm]")
    ax_resid.set_ylabel("Data − Fit", fontsize=9)
    ax_resid.grid(axis="y", alpha=0.3)


def plot_npoints_vs_energy(ax, track_records):
    if not track_records:
        ax.text(0.5, 0.5, "No track data", ha="center", va="center",
                transform=ax.transAxes)
        return

    mean_dedx = np.array([t["mean_dedx"] for t in track_records])
    n_points  = np.array([t["n_points"]  for t in track_records])

    ax.scatter(mean_dedx, n_points, alpha=0.20, s=7, color=BLUE,
               rasterized=True, label="Individual tracks")

    edges = np.unique(np.percentile(mean_dedx, np.linspace(5, 95, 18)))
    prof_x, prof_y, prof_e = [], [], []
    for lo, hi in zip(edges[:-1], edges[1:]):
        sel = n_points[(mean_dedx >= lo) & (mean_dedx < hi)]
        if len(sel) < 3:
            continue
        prof_x.append(0.5*(lo+hi))
        prof_y.append(sel.mean())
        prof_e.append(sel.std() / np.sqrt(len(sel)))
    ax.errorbar(prof_x, prof_y, yerr=prof_e, fmt="o-",
                color=RED, lw=2, ms=5, zorder=5, label="Profile (mean ± SE)")

    # Threshold-scan inset
    thresholds = np.linspace(np.percentile(mean_dedx, 5),
                             np.percentile(mean_dedx, 90), 30)
    avg_pts = [n_points[mean_dedx >= t].mean()
               if (mean_dedx >= t).sum() > 1 else np.nan
               for t in thresholds]
    ax_ins = ax.inset_axes([0.55, 0.55, 0.42, 0.38])
    ax_ins.plot(thresholds, avg_pts, color=ORANGE, lw=1.8)
    ax_ins.set_xlabel("dE/dx threshold", fontsize=7)
    ax_ins.set_ylabel("Mean N pts", fontsize=7)
    ax_ins.set_title("Threshold scan", fontsize=7)
    ax_ins.grid(alpha=0.3)
    ax_ins.tick_params(labelsize=6)

    ax.set_xlabel("Mean dE/dx per track  [ADC / mm]")
    ax.set_ylabel("Centroid points on track  (N)")
    ax.set_title("Track Length vs. Energy Deposition")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)


def plot_padrow_performance(ax_hits, ax_mean, padrow_hits, padrow_dedx):
    if not padrow_hits:
        for ax in (ax_hits, ax_mean):
            ax.text(0.5, 0.5, "No pad-row data", ha="center", va="center",
                    transform=ax.transAxes)
        return

    rows      = np.array(sorted(padrow_hits.keys()), dtype=int)
    hits      = np.array([padrow_hits[r]          for r in rows], dtype=float)
    mean_dedx = np.array([np.mean(padrow_dedx[r]) for r in rows], dtype=float)
    n_r       = np.array([len(padrow_dedx[r])      for r in rows], dtype=float)
    sem_dedx  = np.where(n_r > 1,
                         np.array([np.std(padrow_dedx[r]) for r in rows]) / np.sqrt(n_r),
                         0.0)

    median_hits     = np.median(hits)
    underperforming = hits < 0.5 * median_hits

    ax_hits.bar(rows, hits,
                color=[RED if u else BLUE for u in underperforming],
                edgecolor="none", width=0.85)
    ax_hits.axhline(median_hits,     color=ORANGE, ls="--", lw=1.8,
                    label=f"Median = {median_hits:.0f}")
    ax_hits.axhline(0.5*median_hits, color=RED,    ls=":",  lw=1.5,
                    label="50 % threshold")
    ax_hits.set_ylabel("Total Hits")
    ax_hits.set_xlabel("Pad Row (TPC Layer)")
    ax_hits.set_title("Pad-Row Hit Counts\n(red = < 50 % of median)", fontsize=10)
    ax_hits.legend(fontsize=8)
    ax_hits.grid(axis="y", alpha=0.3)

    global_mean = mean_dedx.mean()
    global_std  = mean_dedx.std()
    ax_mean.errorbar(rows, mean_dedx, yerr=sem_dedx, fmt="o",
                     color=BLUE, ms=5, lw=1.2, capsize=2,
                     label="Mean dE/dx ± SEM")
    ax_mean.axhline(global_mean, color=GREEN, ls="--", lw=1.5,
                    label=f"Global mean = {global_mean:.1f}")
    ax_mean.axhspan(global_mean - 2*global_std,
                    global_mean + 2*global_std,
                    color=GREEN, alpha=0.12, label="±2σ band")
    outlier_mask = np.abs(mean_dedx - global_mean) > 2 * global_std
    if outlier_mask.any():
        ax_mean.scatter(rows[outlier_mask], mean_dedx[outlier_mask],
                        color=RED, zorder=5, s=55, label="Outlier (>2σ)")

    ax_mean.set_ylabel("Mean dE/dx  [ADC / mm]")
    ax_mean.set_xlabel("Pad Row (TPC Layer)")
    ax_mean.set_title("Mean dE/dx per Layer", fontsize=10)
    ax_mean.legend(fontsize=8)
    ax_mean.grid(alpha=0.3)

    bad = list(rows[underperforming])
    if bad:
        print(f"  ⚠  Under-performing pad rows (< 50% median hits): {bad}")
    if outlier_mask.any():
        print(f"  ⚠  Outlier dE/dx pad rows (>2σ): {list(rows[outlier_mask])}")


# ─── Per-file master ──────────────────────────────────────────────────────────

def analyze_file(file_path, output_dir):
    filename = os.path.basename(file_path)
    print(f"\n{'─'*64}\n  {filename}")

    all_dedx, track_records, padrow_hits, padrow_dedx = \
        extract_all_track_data(file_path)

    if len(all_dedx) < 100:
        print(f"  ⚠  Skipping — only {len(all_dedx)} dE/dx values after cuts.")
        return

    fig = plt.figure(figsize=(15, 18))
    fig.patch.set_facecolor("white")
    gs  = gridspec.GridSpec(4, 2, figure=fig,
                            height_ratios=[3, 1, 2.5, 2.5],
                            hspace=0.52, wspace=0.35,
                            left=0.09, right=0.97, top=0.95, bottom=0.06)
    ax_main      = fig.add_subplot(gs[0, :])
    ax_resid     = fig.add_subplot(gs[1, :], sharex=ax_main)
    ax_npts      = fig.add_subplot(gs[2, :])
    ax_hits      = fig.add_subplot(gs[3, 0])
    ax_dedxlayer = fig.add_subplot(gs[3, 1])

    plot_dedx_fit(ax_main, ax_resid, all_dedx, filename)
    plot_npoints_vs_energy(ax_npts, track_records)
    plot_padrow_performance(ax_hits, ax_dedxlayer, padrow_hits, padrow_dedx)

    fig.suptitle(
        f"HIBEAM Prototype TPC  —  {filename}\n"
        f"Tracks: {len(track_records)}  |  chi²/ndf < {CHI2_NDF_MAX}  |  "
        f"dE/dx pts: {len(all_dedx)}",
        fontsize=12, fontweight="bold", y=0.98)

    out = os.path.join(output_dir,
                       filename.replace(".root", "_tpc_analysis.png"))
    plt.savefig(out, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print(f"  ✔  Saved → {out}")


# ─── Batch ────────────────────────────────────────────────────────────────────

def run_batch(input_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    files = sorted(glob.glob(os.path.join(input_dir, "*.root")))
    if not files:
        print(f"No .root files found in {input_dir}")
        return
    print(f"Found {len(files)} ROOT file(s).  Starting batch…\n")
    for f in files:
        try:
            analyze_file(f, output_dir)
        except Exception as e:
            print(f"  ✗  {type(e).__name__}: {e}")
    print(f"\n{'═'*64}\n  Batch complete.")


if __name__ == "__main__":
    INPUT_DIR  = "../experimental_data/"
    OUTPUT_DIR = "analysis_plots/"
    run_batch(INPUT_DIR, OUTPUT_DIR)