//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Mar  2 15:29:57 2026 by ROOT version 6.30/02)
//      from the StreamerInfo in file ../experimental_data/muon_data.root
//////////////////////////////////////////////////////////


#ifndef CentroidData_h
#define CentroidData_h
class CentroidData;

#include "Rtypes.h"

class CentroidData {

public:
// Nested classes declaration.

public:
// Data Members.
   int         y;           //padrow index (kept int to match TrackData)
   float       x;           //[mm]
   float       z;           //[mm] (converted from timestamp)
   float       integrated_ADC_amplitude;    //
   float       sigma_x;                     //
   float       sigma_y;                     //
   float       sigma_z;                     //
   unsigned char used_in_fit;                 //0/1

   CentroidData();
   CentroidData(CentroidData && ) = default;
   CentroidData &operator=(const CentroidData & );
   CentroidData(const CentroidData & );
   virtual ~CentroidData();

};
#endif
