//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Mar 23 02:37:46 2026 by ROOT version 6.38.00)
//      from the StreamerInfo in file ../experimental_data/tracks_centroids_tpc_run_0006-sorted_t0_100.root
//////////////////////////////////////////////////////////


#ifndef TrackData_h
#define TrackData_h
class TrackData;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

class TrackData {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nPoints;     //
   float       slope_xy;    //
   float       intercept_xy;    //
   float       slope_zy;        //
   float       intercept_zy;    //
   vector<int> y;               //
   vector<float> x;               //
   vector<float> z;               //
   vector<float> charge;          //
   vector<float> sigmas_x;        //
   vector<float> sigmas_z;        //
   vector<float> sigmas_y;        //
   float         slope_xy_err;    //
   float         intercept_xy_err;    //
   float         slope_zy_err;        //
   float         intercept_zy_err;    //
   float         cov_xy_is;           //
   float         cov_zy_is;           //
   float         chi2_xy;             //
   int           ndf_xy;              //
   float         chi2ndf_xy;          //
   float         p_xy;                //
   float         chi2_zy;             //
   int           ndf_zy;              //
   float         chi2ndf_zy;          //
   float         p_zy;                //

   TrackData();
   TrackData(TrackData && ) = default;
   TrackData &operator=(const TrackData & );
   TrackData(const TrackData & );
   virtual ~TrackData();

   ClassDef(TrackData,3); // Generated by MakeProject.
};
#endif
