//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Mar 23 02:37:46 2026 by ROOT version 6.38.00)
//      from the StreamerInfo in file ../experimental_data/tracks_centroids_tpc_run_0006-sorted_t0_100.root
//////////////////////////////////////////////////////////


#ifndef CentroidData_h
#define CentroidData_h
class CentroidData;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

class CentroidData {

public:
// Nested classes declaration.

public:
// Data Members.
   int         y;           //padrow index (kept int to match TrackData)
   float       x;           //[mm]
   float       z;           //[mm] (converted from timestamp)
   float       integrated_ADC_amplitude;    //
   float       sigma_x;                     //
   float       sigma_y;                     //
   float       sigma_z;                     //
   unsigned char used_in_fit;                 //0/1
   vector<int>   member_tpc_idx;              //

   CentroidData();
   CentroidData(CentroidData && ) = default;
   CentroidData &operator=(const CentroidData & );
   CentroidData(const CentroidData & );
   virtual ~CentroidData();

   ClassDef(CentroidData,4); // Generated by MakeProject.
};
#endif
