//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Mar 23 02:37:46 2026 by ROOT version 6.38.00)
//      from the StreamerInfo in file ../experimental_data/tracks_centroids_tpc_run_0006-sorted_t0_100.root
//////////////////////////////////////////////////////////


#ifndef tpcData_h
#define tpcData_h
class tpcData;

#include "Rtypes.h"

class tpcData {

public:
// Nested classes declaration.

public:
// Data Members.
   int         val;         //
   int         channel;     //
   int         row;         //
   int         column;      //
   int         timestamp;    //
   int         pedestal;     //
   int         peddev;       //

   tpcData();
   tpcData(tpcData && ) = default;
   tpcData &operator=(const tpcData & );
   tpcData(const tpcData & );
   virtual ~tpcData();

};
#endif
