//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Mar  2 15:29:57 2026 by ROOT version 6.30/02)
//      from the StreamerInfo in file ../experimental_data/muon_data.root
//////////////////////////////////////////////////////////


#ifndef TrackData_h
#define TrackData_h
class TrackData;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

class TrackData {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nPoints;     //
   float       slope_xy;    //
   float       intercept_xy;    //
   float       slope_zy;        //
   float       intercept_zy;    //
   vector<int> y;               //
   vector<float> x;               //
   vector<float> z;               //
   vector<float> charge;          //
   vector<float> sigmas_x;        //
   vector<float> sigmas_z;        //
   vector<float> sigmas_y;        //

   TrackData();
   TrackData(TrackData && ) = default;
   TrackData &operator=(const TrackData & );
   TrackData(const TrackData & );
   virtual ~TrackData();

};
#endif
