//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Mar 13 14:50:24 2026 by ROOT version 6.30/02)
//      from the StreamerInfo in file ../simulation_data/KrakowScatter.root
//////////////////////////////////////////////////////////


#ifndef ProtoTPCHit_h
#define ProtoTPCHit_h
class ProtoTPCHit;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>

class ProtoTPCHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Double_t    xgaus[3];    //
   Double_t    zlandau[40];    //
   int         nHits;          //
   double      SumEdep;        //
   vector<double> Edep;           //
   vector<double> Time;           //
   vector<double> Pos_X;          //
   vector<double> Pos_Y;          //
   vector<double> Pos_Z;          //
   vector<int>    Layer;          //
   int            nSignals;       //
   vector<int>    padRow;         //
   vector<int>    padColumn;      //
   vector<int>    timestamp;      //
   vector<int>    signal;         //

   ProtoTPCHit();
   ProtoTPCHit(ProtoTPCHit && ) = default;
   ProtoTPCHit &operator=(const ProtoTPCHit & );
   ProtoTPCHit(const ProtoTPCHit & );
   virtual ~ProtoTPCHit();

   ClassDef(ProtoTPCHit,2); // Generated by MakeProject.
};
#endif
