//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Mar 13 14:50:24 2026 by ROOT version 6.30/02)
//      from the StreamerInfo in file ../simulation_data/KrakowScatter.root
//////////////////////////////////////////////////////////


#ifndef ScintAna_h
#define ScintAna_h
class ScintAna;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TRandom3.h"

class ScintAna : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nHits;       //
   vector<int> side;        //
   vector<int> layer;       //
   vector<int> bar;         //
   vector<double> nPh1;        //
   vector<double> nPh2;        //
   vector<double> nPh3;        //
   vector<double> nPh4;        //
   vector<double> nPh;         //
   vector<double> Pos;         //
   vector<int>    mult;        //
   vector<double> dE;          //
   vector<double> Esum1;       //
   vector<double> Esum2;       //
   vector<double> Pos1;        //
   TRandom3*      rndm;        //

   ScintAna();
   ScintAna(ScintAna && ) = default;
   ScintAna &operator=(const ScintAna & );
   ScintAna(const ScintAna & );
   virtual ~ScintAna();

   ClassDef(ScintAna,2); // Generated by MakeProject.
};
#endif
